[project]
name = "audiobook-factory"
version = "0.1.0"
description = "Make audiobook for you"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chardet>=5.2.0",
    "click>=8.2.1",
]
